### ISSUE TITLE
Sync: restrict to 1 per recording

### ISSUE THREAD

**Issue by cliona-q** [loopbio/python-motifapi#1]
For our special case using sync during recording to recover audio/video sync, we can have only 1 frame 0 per img_store. Please prevent us from ruining videos by syncing multiple times, e.g. disable sync button after first press during a recording. 

[As we do multiple recordings each day, it would be nice not to have to restart the interface to reset the sync allowance _across_ recordings, so max of 1 _within_ recording would be great]

**Comment by nzjrs** [comment]
fixed in next release
